version: "1.0.0"

# 相关命令权限
# arktools.deathpunish 执行死亡惩罚相关命令的权限
# arktools.hideonmap 执行隐藏雷达相关命令的权限
# arktools.help 查看帮助的权限
# arktools.reload 重载插件的权限
# arktools.setworldborder 更改世界边界的权限
# 其他权限
# arktools.deathpunish.bypass 逃过死亡惩罚


# 更改世界边界
world-border:
  world:
    centerX: 0.0
    centerZ: 0.0
    size: 1000.0
  world2:
    centerX: 0.0
    centerZ: 0.0
    size: 1000.0


# 相关权限
# arktools.deathpunish.bypass 逃过死亡惩罚

# 死亡惩罚
punishments:
  enable: false
  # 死亡是否清除玩家背包
  clearInventory: false
  # 死亡是否清除玩家末影箱
  clearEnderchest: false
  # 死亡是否重置玩家经验值
  resetExp: false
  # 死亡时减少玩家生命上限
  reduceMaxHealth: false
  # 死亡时减少的生命值
  reduceHealthAmount: 2.0
  # 血量上限为1时死亡后是否封禁玩家
  banOnDeath: false
  # 最小生命值
  minHealth: 6.0

  # 触发死亡惩罚信息
  deathMsg: "§4§l你死了，你因此受到了惩罚！"
  # 跳过死亡惩罚
  bypassPunishMsg: "§a你逃过了死亡惩罚！"

  banReason: "§4§l你已经不能再复活了！"






# Squraemap相关

hideOnMap:
  Item:
    material: "COMPASS"
    name: "§b§kAAA§6§l§o隐藏雷达§b§kAAA"